---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - appstudio.redhat.com
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - imagerepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - integrationtestscenarios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaseplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreams/finalizers
  verbs:
  - update
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projectdevelopmentstreamtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projctl.konflux.dev
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
